openapi: 3.0.0
info:
  version: 2.0.0
  title: Next API
  description: A modern API for obtaining transit data for the Portland, OR area.
servers:
  - url: https://example.io/v2
paths:
  /trimet_arrivals:
    get:
      description: Returns arrivals for nearby Trimet stops including route information.
      parameters:
        - $ref: '#/components/parameters/Latitude'
        - $ref: '#/components/parameters/Longitude'
      responses:
        "200":
          description: Successfully returns a list of nearby Trimet stops with arrival information.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - direction
                    - description
                  properties:
                    direction:
                      type: string
                    description:
                      type: string
                    arrivals:
                      type: array
                      items:
                        type: object
                        required:
                          - route
                          - full_sign
                          - short_sign
                          - route_info
                        properties:
                          route:
                            type: string
                          full_sign:
                            type: string
                          short_sign:
                            type: string
                          schedules:
                            type: array
                            items:
                              type: object
                              properties:
                                departed:
                                  type: boolean
                                scheduled:
                                  type: string
                                estimated_arrival:
                                  type: string
                          route_info:
                            type: object
                            required:
                              - route_type
                              - description
                              - frequent_service
                            properties:
                              route_type:
                                type: string
                              description:
                                type: string
                              frequent_service:
                                type: boolean
                              route_color:
                                type: string
  /share_stations:
    get:
      description: Returns nearby micromobility docking stations and status
      parameters:
        - $ref: '#/components/parameters/Latitude'
        - $ref: '#/components/parameters/Longitude'
      responses:
        "200":
          description: Successfully returns a list of nearby micromobility docking stations.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: '#/components/schemas/ShareStation'
  /drive_times:
    get:
      description: Returns nearby ODOT drive time data from origins to destinations.
      parameters:
        - $ref: '#/components/parameters/Latitude'
        - $ref: '#/components/parameters/Longitude'
      responses:
        "200":
          description: Successfully returns a list of nearby drive times to destinations.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DriveTimes'
  /micromobility:
    get:
      description: Returns nearby micromobility devices (scooters, bikes and more).
      #  ----- Added lines  ----------------------------------------
      parameters:
        - $ref: '#/components/parameters/Latitude'
        - $ref: '#/components/parameters/Longitude'
        - name: brand
          in: query
          description: The brand of micromobility device. Optional. Omit to return all available.
          schema:
            type: string
      #  ---- /Added lines  ----------------------------------------
      responses:
        "200":
          description: Successfully returns a list of nearby micromobility devices.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MicromobilityDevice'
components:
  schemas:
    Distance:
      type: object
      required:
        - distance
      properties:
        distance:
          type: integer
    Brand:
      type: object
      required:
        - brand
      properties:
        brand:
          type: string
    Location:
        type: object
        required:
            - lat
            - lon
        properties:
            lat:
              type: string
            lon:
              type: string
    MicromobilityDevice:
      allOf:
        - $ref: '#/components/schemas/Distance'
        - $ref: '#/components/schemas/Brand'
        - $ref: '#/components/schemas/Location'
        - required:
            - uuid
        - properties:
            uuid:
              type: string
    HighwayProperties:
      properties:
        direction:
          type: string
        cross_street:
          type: string
        highway_type:
          type: string
    HighwayDestination:
      allOf:
        - $ref: '#/components/schemas/HighwayProperties'
        - properties:
            destination_id:
              type: integer
            route_destination:
              type: string
            minimum_route_time:
              type: integer
            travel_time:
              type: integer
            delay:
              type: integer
    DriveTime:
      allOf:
        - $ref: '#/components/schemas/Location'
        - $ref: '#/components/schemas/HighwayProperties'
        - properties:
            origin_id:
              type: integer
            location_name:
              type: string
            destinations:
              type: array
              items:
                type: object
                $ref: '#/components/schemas/HighwayDestination'
    ShareStation:
      allOf:
        - $ref: '#/components/schemas/MicromobilityDevice'
        - properties:
            name:
              type: string
            capacity:
              type: integer
            station_status:
              type: object
              properties:
                docks_available:
                  type: integer
                accepts_returns:
                  type: boolean
                vehicles_available:
                  type: integer
                renting:
                  type: boolean
  parameters:
    Latitude:
      name: lat
      in: query
      description: The latitude coordinate of your location.
      schema:
        type: number
    Longitude:
      name: lon
      in: query
      description: The longitude coordinate of your location.
      schema:
        type: number